# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  - master

pool:
  name: DemoAgent
  demands:
    - Agent.Name -equals PracticeAgent

steps:
- task: Maven@4  # Use Maven@4 (Recommended)
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'  # Use '22' if supported
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    goals: 'clean package'

- task: PublishTestResults@2  # Publish test results separately
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    searchFolder: '$(System.DefaultWorkingDirectory)'
    failTaskOnFailedTests: true

- task: CopyFiles@2
  inputs:
    Contents: '**/*.war'  # Corrected pattern
    TargetFolder: '$(build.artifactstagingdirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'warfile'
    publishLocation: 'Container'